//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.3309.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BBDEVDays2024.UIModel
{

/// <summary>
/// Represents the UI model for the 'USR BIOEXTENSION Edit Form' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModelMetadata(global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit, "b9c4688b-6f1d-498f-9184-c42a3d125a59", "2cd4dc50-a95a-4c41-b76a-57947ca9828f", "CONSTITUENT")]
public partial class @USRBIOEXTENSIONEditFormUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataFormUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _extensionfield1;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _extensionfield2;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3309.0")]
	public @USRBIOEXTENSIONEditFormUIModel() : base()
	{


        _extensionfield1 = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _extensionfield2 = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.Mode = global::Blackbaud.AppFx.UIModeling.Core.DataFormMode.Edit;
        this.DataFormTemplateId = new System.Guid("b9c4688b-6f1d-498f-9184-c42a3d125a59");
        this.DataFormInstanceId = new System.Guid("2cd4dc50-a95a-4c41-b76a-57947ca9828f");
        this.RecordType = "CONSTITUENT";
        this.FixedDialog = true;
        this.ExtensionTabCaption = "TabCaption";
        this.UserInterfaceUrl = "browser/htmlforms/custom/bbdevdays2024/USRBIOEXTENSIONEditForm.html";

        //
        //_extensionfield1
        //
        _extensionfield1.Name = "EXTENSIONFIELD1";
        _extensionfield1.Caption = "Extensionfield1";
        this.Fields.Add(_extensionfield1);
        //
        //_extensionfield2
        //
        _extensionfield2.Name = "EXTENSIONFIELD2";
        _extensionfield2.Caption = "Extensionfield2";
        _extensionfield2.MaxLength = 200;
        _extensionfield2.Multiline = true;
        this.Fields.Add(_extensionfield2);

		OnCreated();

	}

    /// <summary>
    /// Extensionfield1
    /// </summary>
    [System.ComponentModel.Description("Extensionfield1")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3309.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @EXTENSIONFIELD1 {
		get { return _extensionfield1; }
	}

    /// <summary>
    /// Extensionfield2
    /// </summary>
    [System.ComponentModel.Description("Extensionfield2")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.3309.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @EXTENSIONFIELD2 {
		get { return _extensionfield2; }
	}

}


}
